# Generated by Django 2.2.5 on 2022-12-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Category', models.CharField(max_length=50)),
                ('Delivery_Time', models.IntegerField(default=0)),
                ('Rating', models.FloatField(default=5.0)),
                ('Stock', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('Sales_count', models.IntegerField(default=0)),
            ],
        ),
    ]
